version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".dialyzer_ignore.exs",
 ".formatter.exs",
 ".github/dependabot.yml",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "hw/hw.md",
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "hw/assets/TSW19001_NERVESKEY_X1_SCH.PDF"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Custom Electronics"
SPDX-License-Identifier = "SHL-0.51"

[[annotations]]
path = [
 "hw/assets/assembled.jpg",
 "hw/assets/bottom_mount.jpg"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

